### ISSUE TITLE
Buggy audio in some apps/games (only found one game so far)

### ISSUE THREAD

**Issue by Nixola** [TheWhisp/android_device_samsung_msm7x27a-common#102]
I'm encountering some bugs with sound effects on Bloon Tower Defense 5. It shouldn't be a game bug, since it works fine on other Android devices (I couldn't test any other device with CM though). Sometimes, when many sounds are played in a short time, both the sounds and the music stop playing. If there's anything else I can do to help you solving this bug or if you just don't want to fix it since it doesn't matter to you please let me know
EDIT: oh, I forgot to tell you that I'm using the Jenad 29-9-13 build on a GT-S6500D

**Comment by Nixola** [comment]
Duplicate? What's the other one? I've read the whole list of both open and closed issues and I couldn't find any

**Comment by TheWhisp** [comment]
Somebody I already opened a similar issue. I have no problems with audio.

**Comment by Nixola** [comment]
It's not the whole audio, it works fine almost everywhere, it's just one single game so far that gives me some issues; and the issue is different, it's not laggy but sometimes when I play it just stops. If you don't wanna fix it it's fine anyway, you already did a wonderful job and I can surely play without sound
