### ISSUE TITLE
Battery percentage

### ISSUE THREAD

**Issue by ghost** [TheWhisp/android_device_samsung_msm7x27a-common#106]
My battery was 99% then I restarted the phone and it was 1%
Charged it, went to 100% in less than 15 minutes.
I tried to calibrate the battery and it's still the same.
Device: GT-S6500D on 29/9 Build

I flashed 11/9 build, battery is acting normally.

**Comment by TheWhisp** [comment]
I have never had this issue.

**Comment by ghost** [comment]
Well as I said I am having this issue. So the least you can do is help me solve it, not deny there is one in the first place.

**Comment by TheWhisp** [comment]
This is certainly not ROM related. If it were, everyone would have that problem. Think.

**Comment by ghost** [comment]
What else could it be? What do you think would cause this? Battery is working fine on 11/9 build.

**Comment by NaokiXie** [comment]
install CPUspy or any related programs to see what makes the battery drain.

its odd that youre the only one having this problem while me and others doesnt have that.
the problem is in your end.
