### ISSUE TITLE
CLock rendering issue

### ISSUE THREAD

**Issue by pgcristyan** [TheWhisp/android_device_samsung_msm7x27a-common#108]
![2013-10-08 10 38 14](https://f.cloud.github.com/assets/5278645/1287395/b07b9328-2ff4-11e3-9e05-2b0e0ab57f20.png)

I know this is an old bug but it has returned in the latest 29/09/2013 build.

**Comment by Xiphled** [comment]
As a workaround I just changed that widget to the plain clock one ( without the date under) so it looks fine. At least until it'll get fixed.(if it will).
