### ISSUE TITLE
Reboot 

### ISSUE THREAD

**Issue by george99** [TheWhisp/android_device_samsung_msm7x27a-common#111]
Hi this is an issue that drives me crazy.When my S6500D is charged to 100% and i disconnect my phone from the charger and go to sleep mode after 10-15 seconds it reboots itself.And now when i go to sleep mode it reboots every time . I wipe the data and cache but it keeps rebooting.PLEASE FIX THIS !!!

**Comment by TheWhisp** [comment]
I don't have this problem. No one has it but you.
