### ISSUE TITLE
reboot fix 

### ISSUE THREAD

**Issue by arthurvigen** [TheWhisp/android_device_samsung_msm7x27a-common#112]
i think i have solved that problemm

settings:ondemand,noop 246-1156mhz

**Comment by TheWhisp** [comment]
stop spamming here. Your device can't handle OC, so don't do it.

**Comment by arthurvigen** [comment]
but before it could

**Comment by george99** [comment]
Thanks arthurvigen you helped me A LOT !!!

**Comment by arthurvigen** [comment]
youre welcome
