### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ZupperMannRO** [TheWhisp/android_device_samsung_msm7x27a-common#118]
I can't install cyanogenmod even with clockworkmod. And something more! I was needed to reinstall stock rom BECAUSE YOUR BLOODY CLOCKWORKMOD 6 DESTROYED OLD ONE. When I starting the phone only the clockworkmod was starting. I had 2.3.6 xxlc4 stock, no root. Need solution for both problems. I have S6500D from Romania. And I lost ALL MY DATA... hate clockworkmod 6

**Comment by ZupperMannRO** [comment]
I tried to install CM 10.1 if u want to know...

**Comment by TheWhisp** [comment]
Since when this has become some kind of help center? Anyway, keep going, it's kind of funny.
