### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by MahmoudElghzaly** [TheWhisp/android_device_samsung_msm7x27a-common#120]
a white screen apperce when i press the lock key to unlock the screen

**Comment by TheWhisp** [comment]
so?

**Comment by MahmoudElghzaly** [comment]
so what ????
this is a problem with me ..... how can i solve it ?????
sorry for my english and thnx for care

**Comment by bqubique** [comment]
all you can do is Nothing , I'm really sorry for you , but this WAS a KNOWN BUG/Problem , and as it seems , it won't be fixed ever .It doesn't happen to TheWhisp , he has NO problems .He is building CM for himself and he just Shares that work with us .That's it

**Comment by MahmoudElghzaly** [comment]
if he is building it for him self it will not be a problem .... thnx for his work its really good
but the thing which makes me wonder is that his device is the same as my device .... how this rom works good with him and not with me 
sorry for my bad english

**Comment by TheWhisp** [comment]
It works good for a lot of people. While the device is the same, modem (baseband) can be different, board HW rev can be different etc.

**Comment by MahmoudElghzaly** [comment]
aha i understand now
thnx for replay 
but can you fix this problem ?????? ... more than one want to use your CM but they have my problem

**Comment by MahmoudElghzaly** [comment]
wait ..... i have remembered some thing
there was a nightly bulit for that CM 
when i flashed it is worked good and that problem was solved but there was only a problem with the camera..... could you solve the problem of the camera in that CM
.
.
.
sorry for my english and thnx for your care
