### ISSUE TITLE
Battery drain - internet connection

### ISSUE THREAD

**Issue by ahcimm** [TheWhisp/android_device_samsung_msm7x27a-common#124]
I have the latest CM 10.1 11/10/2013
and im experiencing quite big battery drain. 
it usually happens when i turn on internet connection 'via gsm'.

it drains a bit less when the phone is connected by wi fi

when i say that phone is connected to internet i mean that connection is turned on without any extremely high usage of the phone. few calls few sms few email checks.

turning on internet connection only when i need to check something drains battery  for something like 25 % - 35% per day depending on phone usage.
with internet connection turned on im always worried that battery will last until the evening

of course you can say that i can turn it on and off every time but... that's not a solution of a problem when u want to be online for a whole day.

Thanks a lot for all of your work!
Michal
![2013-10-24 21 49 46](https://f.cloud.github.com/assets/5768482/1402626/3ecf737a-3ce7-11e3-9910-d277c56be6ea.png)
![2013-10-24 21 51 48](https://f.cloud.github.com/assets/5768482/1402627/3ed0967e-3ce7-11e3-88be-f6f08fff01b1.png)

**Comment by TheWhisp** [comment]
that's not anything ROM specific. Deal with it.

**Comment by ahcimm** [comment]
so you say that when i leave the phone for a whole day doing nothing with internet on, it should drain a whole battery?

**Comment by ahcimm** [comment]
ok i guess i have found a solution -> 
http://forum.xda-developers.com/showthread.php?t=2385843
