### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by chiwbicka** [TheWhisp/android_device_samsung_msm7x27a-common#128]
For devices that has white screen bug!!!

I have also the white screen bug with the latest update, but whit the cm-10.1-20130707-UNOFFICIAL-jena.zip mod (with working camera) there is no bug. After i try cm-10.1-20130718-UNOFFICIAL-jena.zip and the white screen bug appears also.

**Comment by TheWhisp** [comment]
cool story, bro
