### ISSUE TITLE
not working bluetoot and camera on samsung galaxy mini 2 s6500d CM 10.1 jena

### ISSUE THREAD

**Issue by rcmcaca** [TheWhisp/android_device_samsung_msm7x27a-common#133]
if bluetooth enable not working although searching device but not find anyone device, and camera not working..

**Comment by rcmcaca** [comment]
![screenshot_2013-11-09-08-25-03](https://f.cloud.github.com/assets/5893152/1505596/03a26930-48de-11e3-9f9b-8218bbdaf8d7.png)
![screenshot_2013-11-09-08-25-37](https://f.cloud.github.com/assets/5893152/1505597/0491ee9c-48de-11e3-8247-d34232cda66e.png)

**Comment by TheWhisp** [comment]
Look at your build date lol

**Comment by rcmcaca** [comment]
Have expired? 
Can you give me the link to download the new version of cyanogenmod 10.1?

**Comment by iformas** [comment]
http://goo.im/devs/thewhisp/jena-cm10.1

**Comment by rcmcaca** [comment]
thanks..

**Comment by rcmcaca** [comment]
![untitled](https://f.cloud.github.com/assets/5893152/1546555/2659d40a-4d88-11e3-90ba-e34f71d36dc3.png)
I can't download from this link?
