### ISSUE TITLE
home button does not wake device in deep sleep

### ISSUE THREAD

**Issue by vickygcoolest** [TheWhisp/android_device_samsung_msm7x27a-common#14]
in cm roms home button wakes the device when not in deep sleep but as soon the device goes in deep sleep home button doesnt wake the device only power button can wake the device in that situation !!!
device - ace plus (gt s7500)

**Comment by TheWhisp** [comment]
Does it work on stock ROM?

**Comment by vickygcoolest** [comment]
yes it works flawlessly in stock rom and other custom roms based on stock rom

**Comment by vickygcoolest** [comment]
i have installed cpu spy which tells that device is going in deep sleep or not and at which time 
and what i noticed was in cm 10.1 when deep sleep didn't happened phone was waking through home button and when the deep sleep happened home button did not responded (checked that later by viewing cpu spy states)

**Comment by bqubique** [comment]
Sometimes pressing it more than 8-10 times , it wakes the device from deep sleep , but pressing it once , won't wake the device up .

**Comment by galaxyfreak** [comment]
Ever fixed?

**Comment by vickygcoolest** [comment]
it is fixed in kernel 3.0.xx
