### ISSUE TITLE
cant download cm from this link?

### ISSUE THREAD

**Issue by rcmcaca** [TheWhisp/android_device_samsung_msm7x27a-common#140]
![untitled](https://f.cloud.github.com/assets/5893152/1560341/c8e64006-5002-11e3-859f-0a375dc17958.png)

I can't download from this link?

**Comment by razvanalex101** [comment]
I have the same error report,is there a second link to download?

**Comment by rcmcaca** [comment]
I use cm-10.2-20130918-UNNOFICIAL-jenad, and cwm 6.0.3.6-jena, but i try to restore to ginggerbread cannot, sudenly restart,it has not even finished the restore..

what should I do?
