### ISSUE TITLE
sdcard external,camera not work on cm-10.2-20130918-UNNOFICIAL-jenad

### ISSUE THREAD

**Issue by rcmcaca** [TheWhisp/android_device_samsung_msm7x27a-common#141]
I use cm-10.2-20130918-UNNOFICIAL-jenad, and cwm 6.0.3.6-jena, but i try to restore to ginggerbread cannot, sudenly restart,it has not even finished the restore..

what should I do?

**Comment by rcmcaca** [comment]
whether the bad risk is often replaced the firmware?

**Comment by rcmcaca** [comment]
Bluetooth cannot be used..

**Comment by TheWhisp** [comment]
don't report bugs if you're using older build
