### ISSUE TITLE
CWM isn't making backup of .android_secure in internal SD Card.

### ISSUE THREAD

**Issue by SilicaAnimus** [TheWhisp/android_device_samsung_msm7x27a-common#143]
I hope this place is also for reporting bugs in CWM. 

Nandroid in CWM for GT-S6500, he is not making backup of .android_secure stored on internal SD Card, so he isn't doing backups of apps moved here.

**Comment by TheWhisp** [comment]
which version?

**Comment by SilicaAnimus** [comment]
6.0.3.3-b2. 6.0.3.6 crashing instead of making backup.

**Comment by TheWhisp** [comment]
it's fixed on the latest 6.0.4.5 recovery build, so I closing this. I'll release it later.

**Comment by SilicaAnimus** [comment]
I updated to 6.0.4.5 and it still isn't working.

**Comment by TheWhisp** [comment]
I just tested and it is working fine for me

**Comment by SilicaAnimus** [comment]
I choosed backup to sdcard1, previously I moved some apps to SD and I don't have .android_secure.vfat in copy, also log says: 

Backup of data completed.
No .android_secure found. Skipping backup of applications on external storage.
Backing up cache...

**Comment by TheWhisp** [comment]
hmm.. as I said works fine for me. At least on latest cm-10.2. Old builds are unsupported.

**Comment by SilicaAnimus** [comment]
I'm using latest CM10.1, as CM10.2 is falling into bootloop on my device.
Both of them should use this same patch for .android_secure, so it is
strange.

**Comment by TheWhisp** [comment]
if you have the bootloop on latest cm10.2, it means that sdcard0 cannot mount in recovery, that's why .android_secure is not found. Re-partition your device with odin.

**Comment by SilicaAnimus** [comment]
Can I restore nandroid backup after this operation in order to save my data?
