### ISSUE TITLE
sdcard external,camera not work on cm-10.2-20130918-UNNOFFICIAL-jenad (nightly)

### ISSUE THREAD

**Issue by rcmcaca** [TheWhisp/android_device_samsung_msm7x27a-common#144]
I use cm-10.2-20130918-UNNOFFICIAL-jenad (nightly), and cwm 6.0.3.6-jena, but i try to restore to ginggerbread cannot, sudenly restart,it has not even finished the restore..

what should I do?

**Comment by rcmcaca** [comment]
it includes the latest version right?

**Comment by TheWhisp** [comment]
can't you read? DON'T REPORT BUGS IF YOU USE OLDER BUILDS!

**Comment by rcmcaca** [comment]
I can read..:p
how is the solution? sorry I am still a beginner, please guidance, thank you.
