### ISSUE TITLE
flashlight not working

### ISSUE THREAD

**Issue by vickygcoolest** [TheWhisp/android_device_samsung_msm7x27a-common#15]
flashlight is not working in cm roms 
willing to add logcat if someone is interested to help us  
device - ace plus(gt s7500)

**Comment by vickygcoolest** [comment]
ohk 
some development around here 
torch works through kernel  but not by cameraHAL
 camera flashlight still don't work

**Comment by TheWhisp** [comment]
With those permission changes?

**Comment by TheWhisp** [comment]
Try:

chmod 0660 /sys/class/camera/rear/rear_flash
chown system.camera /sys/class/camera/rear/rear_flash

**Comment by vickygcoolest** [comment]
no without that also 
the app that is adjustable torch deals directly with sysfs instead of cameraHAL 

i tried that comand also but still there is no flash in camera

**Comment by vickygcoolest** [comment]
now we got cm torch working also 
http://forum.xda-developers.com/showthread.php?t=2416167
dude i have a question in my mind ......
can we make camera flash such that it also uses kernel(sysfs) instead of cameraHAL????
this may be a silly question but just want to know

**Comment by TheWhisp** [comment]
no. Flash is enabled via libcamera.so and liboemcamera.so. liboemcamera communicates with kernel. libcamera makes it work when taking a picture. You need to try with Ace Plus libs and upload a camera log here.

**Comment by vickygcoolest** [comment]
tried to replace 
libcamera.so
lioemcamera.so
camera.msm7x27a.so at once 
rom booted but error is cannot connect to camera 
logcat-
http://pastebin.com/download.php?i=CL3PYAfy

**Comment by TheWhisp** [comment]
can you find that libstagefright.so I uploaded some time ago and try with it?

edit: but before that, can you rename every msm7x27a in /system/lib/hw/ to msm7627a and also the same in build.prop? Then reboot and try again. For some reason, libcamera cannot determine the target platform

**Comment by vickygcoolest** [comment]
ohk will try again now

**Comment by vickygcoolest** [comment]
tried that too 
renamed all files in hw folder with msm7627a and in build prop to (ro.board.platform=msm7627a)
same error 'cannot connect to camera'
changed files- libcamera.so and  lioemcamera.so(stock) 
camera.msm7x27a.so and libstagefright.so(modified)
Line 4449: E/QualcommCameraHardware(  117): FATAL ERROR: could not dlopen liboemcamera.so: Symbol not found: soinfo_relocate(linker.cpp:1013): cannot locate symbol "__htclog_init_mask" referenced by "libsrsfx.so"...
    Line 4449: E/QualcommCameraHardware(  117): FATAL ERROR: could not dlopen liboemcamera.so: Symbol not found: soinfo_relocate(linker.cpp:1013): cannot locate symbol "__htclog_init_mask" referenced by "libsrsfx.so"...
logcat-
http://pastebin.com/download.php?i=RD6YKkmt

**Comment by TheWhisp** [comment]
we need this: https://github.com/CyanogenMod/android_system_core/commit/f7ac9ae1c0dfccdbc441a5c64ae843bc3c56ff1d

**Comment by vickygcoolest** [comment]
so this will be implemented in future builds ??
asking this because i didn't get what was that !!!

**Comment by ShadowsDie** [comment]
hey TheWhisp, can you explain that? i really don't understand what need from that
