### ISSUE TITLE
Cm10.2

### ISSUE THREAD

**Issue by Mada12345** [TheWhisp/android_device_samsung_msm7x27a-common#153]
Hey thewhisp Please Tell me how to  re-partition with odin :)

**Comment by Mada12345** [comment]
What should i do ?

**Comment by TheWhisp** [comment]
just tick the "re-partition" check-box

**Comment by Mada12345** [comment]
Oki I know man but when when i Download new cwm Check on it or When i open recovery pls Write me steps when i Work on odin The mob In downloadmode Write me steps To Know how t

**Comment by Mada12345** [comment]
to know more pls .. thanks

**Comment by Mada12345** [comment]
I Read on the internet re-partiton Format System On cwm I can do it !! Without partion

**Comment by TheWhisp** [comment]
cwm cannot re-partition your device, only format some of the partitions on it

**Comment by Mada12345** [comment]
Oki . What steps after i check The box !? Iwant to download 4.3 but i cant pls Man write me steps how to re-partiton My device

**Comment by Mada12345** [comment]
!?
