### ISSUE TITLE
CM10.2 not start on my GT-S6500L

### ISSUE THREAD

**Issue by Brunever123** [TheWhisp/android_device_samsung_msm7x27a-common#154]
I have a GT-S6500L and when I install the ROM does not pass the bootanimation!

I always do Wipes and format (system / cache / data) but still not working.

My friend has a GT-S6500L already if it works ... Thanks in advance

**Comment by TheWhisp** [comment]
I don't have the L variant. How do you expect me to look into this problem?

**Comment by Mada12345** [comment]
Thats my bug too but Im 6500D I Dosen't pass too . in the pervious i told thewhisp the steps to re-partiton my mob but he didn't tell me anything :( !!!

**Comment by Mada12345** [comment]
if you can fix it without partiton and odin .. thank U for that

**Comment by Brunever123** [comment]
I just want you to see my problem to see if you have any solution!

It does not pass the bootanimation, it stays there and vibrates every 25 seconds and does not start. Sorry for the inconvenience po
