### ISSUE TITLE
Re-partiton by odin !! 

### ISSUE THREAD

**Issue by Mada12345** [TheWhisp/android_device_samsung_msm7x27a-common#157]
Steps For re-partition Please

**Comment by Mada12345** [comment]
Thewhisp The re-partiton !! how  can i do thaat !!!!

**Comment by sruu132** [comment]
Hey 
I solved problem with internal sd in our galaxy mini 2
You need 
-Odin3
-Drivers for S6500D

*.pit file : http://www4.zippyshare.com/v/12040816/file.html (you must unzipping)
How to install:
-connect phone in download mode
-put *.pit file to [PIT] in odin (Automatically selects the option to re-partition it should not be characterized.)
-press [Start] button and wait few minutes

NOTE! All files from the internal memory should not be deleted!

sorry for my bad english

**Comment by george99** [comment]
Thank you ! You are a life saver !
