### ISSUE TITLE
Couldn't mount sdcard0 

### ISSUE THREAD

**Issue by Mada12345** [TheWhisp/android_device_samsung_msm7x27a-common#159]
At the first I want to tell u Thanks For this wonderful build 18/12 That's Very Wonderful But U forget on thing Sdcard 0 I can't mount it Can u fix ? .. Waiting the best ;)

**Comment by Mada12345** [comment]
Sry I forgot One thing at cwm 6,0.45 I Doesn't mount sdcard 0 only sdcard 1 !!!

**Comment by Mada12345** [comment]
I Can't mount **

**Comment by TheWhisp** [comment]
mounts perfectly on my device. Re-partition using odin

**Comment by Mada12345** [comment]
Pls Tell mee how to re-partition !!

**Comment by sruu132** [comment]
Hey 
I solved problem with internal sd in our galaxy mini 2
You need 
-Odin3
-Drivers for S6500D

*.pit file : http://www4.zippyshare.com/v/12040816/file.html (you must unzipping)
How to install:
-connect phone in download mode
-put *.pit file to [PIT] in odin (Automatically selects the option to re-partition it should not be characterized.)
-press [Start] button and wait few minutes

NOTE! All files from the internal memory should not be deleted!

sorry for my bad english

**Comment by george99** [comment]
hey this file is for s6500 not for s6500D please upload for S6500D

**Comment by sruu132** [comment]
This file is for S6500D (without NFC).

**Comment by aPlays** [comment]
I give it a try

**Comment by aPlays** [comment]
Thanks man!!! It's worked! _-_
