### ISSUE TITLE
Cyanogen11 Problems on Galaxy Mini 2

### ISSUE THREAD

**Issue by rasoolsn2014** [TheWhisp/android_device_samsung_msm7x27a-common#160]
01 - Screen resolution problems in Lock Screen
02 - Not transparent status bar
03 - There is no light adjustment control in the status bar
04 - a slight lag between movements in the Notification bar & Menu
05 - No personalization settings. Personalization settings such as Cyanogen10.1 & 10.2
06 - File manager has a problem.
07 - Gallery and Picture Settings messages to FC
08 - There is no option to add widgets on the lock screen
09 - settings GoogleNow has a problem.
10 - no transparent notification bar
11 - External SD Card is not supported.
12 - Features options interface is very low.
13 - Security settings are not perfect (like Cyanogen10.1 & 10.2)

**Comment by sipe** [comment]
White fucking screen. 
Here are logs, I'm hoping that they are showing more then in CM10.2
http://s000.tinyupload.com/index.php?file_id=49634543916352213849

**Comment by Mada12345** [comment]
You can Change Bootimg. From 7/7 To any build But the wifi didn't turn On

**Comment by Mada12345** [comment]
Rasoolsn That is the first Build Of Kitkat .. The whisp Will Fix all thats things In the coming Builds

**Comment by rasoolsn2014** [comment]
I know my friend ..
I just do the job myself as a tester.

**Comment by TheWhisp** [comment]
lol. I am not even going to spend my time responding to you. Which I already did. Damn. Anyway, Google is your answer.

**Comment by sruu132** [comment]
AD 11

Hey 
I solved problem with internal sd in our galaxy mini 2
You need 
-Odin3
-Drivers for S6500D

*.pit file : http://www4.zippyshare.com/v/12040816/file.html (you must unzipping)
How to install:
-connect phone in download mode
-put *.pit file to [PIT] in odin (Automatically selects the option to re-partition it should not be characterized.)
-press [Start] button and wait few minutes

NOTE! All files from the internal memory should not be deleted!

sorry for my bad english
