### ISSUE TITLE
Mobile Brick when i repartition it !!

### ISSUE THREAD

**Issue by Mada12345** [TheWhisp/android_device_samsung_msm7x27a-common#163]

**Comment by Mada12345** [comment]
Why you do that . ithink You don't Know how to repartition

**Comment by TheWhisp** [comment]
stop spamming here, goddammit.

**Comment by Mada12345** [comment]
Oki Iwill Stop if you tell me how To repartition By odin Google Not the answer All people Not tell the steps TheY Told That It will brick The mob mob i asked u many times And u close the issue Pls tell me How can i do that and I will not Open Any Issue again
