### ISSUE TITLE
deep sleep wake up problem CM 11

### ISSUE THREAD

**Issue by cozmin** [TheWhisp/android_device_samsung_msm7x27a-common#165]
Great rom TheWhisp ! I don't have the white screen problem anymore with CM 11. If you could include the fix in the other rom's it will be great :D
I don't know if i am the only one with the problem ( i can't post on the xda thread sorry) so here it goes : after a while when i try to turn the screen on it doesn't want to , first time when i try the touch sensitive keys light up but not the screen , the second time nothing happens at all . I have to restart the phone to get it to work . 
Do you have any ideea why ?

**Comment by arthur13** [comment]
i have this problem too
