### ISSUE TITLE
Can't mount internal SD card

### ISSUE THREAD

**Issue by george99** [TheWhisp/android_device_samsung_msm7x27a-common#166]

**Comment by TheWhisp** [comment]
no problems for me

**Comment by sruu132** [comment]
Hey 
I solved problem with internal sd in our galaxy mini 2
You need 
-Odin3
-Drivers for S6500D

*.pit file : http://www4.zippyshare.com/v/12040816/file.html (you must unzipping)
How to install:
-connect phone in download mode
-put *.pit file to [PIT] in odin (Automatically selects the option to re-partition it should not be characterized.)
-press [Start] button and wait few minutes

NOTE! All files from the internal memory should not be deleted!

sorry for my bad english

**Comment by george99** [comment]
Hey Please update the link i have S6500D non NFC !

**Comment by sruu132** [comment]
This file is for mini 2 without NFC.
