### ISSUE TITLE
SDCard0 can't mount, moving app on SD Card is impossible

### ISSUE THREAD

**Issue by konkretny** [TheWhisp/android_device_samsung_msm7x27a-common#168]
Hi,

CM version problem: CM11 20131218 on GT-S6500D

Problems:
1. I can't mount SDCard0
2. I can't moving app on SD Card
3. I can not set my ringtone

Re-partition on Odin and wipe/reset does not solve the problem.

**Comment by TheWhisp** [comment]
1. duplicate, re-partition with odin
2. works fine on my device
3. works fine on my device

**Comment by george99** [comment]
I have the same problem please fix it.

**Comment by sruu132** [comment]
Hey 
I solved problem with internal sd in our galaxy mini 2
You need 
-Odin3
-Drivers for S6500D
- *.pit file : http://www4.zippyshare.com/v/12040816/file.html (you must unzipping)

How to install:
-connect phone in download mode
-put *.pit file to [PIT] in odin (Automatically selects the option to re-partition it should not be characterized.)
-press [Start] button and wait few minutes

NOTE! All files from the internal memory should not be deleted!

sorry for my bad english

**Comment by george99** [comment]
Hey the link you gave me is dead please REPLY!

**Comment by sruu132** [comment]
Re-upload:
https://drive.google.com/file/d/0B-g0fkTtxB94cGdlQ0lsM3ZBekU/edit?usp=sharing

**Comment by subki** [comment]
Solved, thank so much for shared information...

**Comment by JTeeDubb** [comment]
Didnt work for me, Failed write on odin on S6500T Running Cm11
