### ISSUE TITLE
Menu and back keys do not turn off

### ISSUE THREAD

**Issue by ghost** [TheWhisp/android_device_samsung_msm7x27a-common#17]
If I leave the device in lock screen (the device is still locked), the screen turns off after a short amount of time, but the menu and back keys don't turn off along with the screen.

**Comment by TheWhisp** [comment]
I don't have this issue. Can anyone else confirm?

**Comment by NaokiXie** [comment]
I experienced it but wiping data/cache solved the issue. therefore it can be an app issue.
