### ISSUE TITLE
keyboard & browser

### ISSUE THREAD

**Issue by octaviojss** [TheWhisp/android_device_samsung_msm7x27a-common#170]
When i installed the latest rom (27/12/2013) in my s6500, the keyboard was constantly crashing.
Also the browser wouldnt open.

**Comment by TheWhisp** [comment]
I test all releases, there are no such problems

**Comment by octaviojss** [comment]
Then what do you suggest? 

Dāvis Mālnieks notifications@github.com escreveu:

**Comment by octaviojss** [comment]
Well it was my mistake. I installed the wrong version of gapps. 
My bad. 

Dāvis Mālnieks notifications@github.com escreveu:
