### ISSUE TITLE
Lastet update cwm 6.0.4.5 can't mount scard0...!(NOT duplicate!)

### ISSUE THREAD

**Issue by almir77** [TheWhisp/android_device_samsung_msm7x27a-common#171]
Lastet update cwm 6.0.4.5 cant mount scard0 even when repartitioned in odin for
jena GT-S6500, nfc model(at least). SO you can not see any zip file to scard0 by using cwm 6.0.4.5 to flash.
There' s NO .android_secure in backing up previous rom, so you can not restore it back...!
Maby this is a serious problem of CWM 6.0.4.5...!!!

**Comment by TheWhisp** [comment]
already discussed multiple times

**Comment by almir77** [comment]
Yes but slill an issue you closed whithout a solution.

**Comment by sruu132** [comment]
Hey 
I solved problem with internal sd in our galaxy mini 2
You need 
-Odin3
-Drivers for S6500D

*.pit file : http://www4.zippyshare.com/v/12040816/file.html (you must unzipping)
How to install:
-connect phone in download mode
-put *.pit file to [PIT] in odin (Automatically selects the option to re-partition it should not be characterized.)
-press [Start] button and wait few minutes

NOTE! All files from the internal memory should not be deleted!

sorry for my bad english

**Comment by almir77** [comment]
As i sed above, i made the repartition in odin 3.x but the .pit file isnt working for the jena
GT-S6500 NFC MODELS....!
Odin says: SECURE CHECK FAIL : ID 0x95
Do you have a .pit file working for nfc models jena???
I appreciate your answer !!!

**Comment by sruu132** [comment]
For variant with NFC there is no such file.

**Comment by almir77** [comment]
Sruu132, i didnt understand you!
Is there any .pit file working for my case or you will live us behind,
because we have GT-S6500 and not GT-S6500D...???

**Comment by Mada12345** [comment]
romeo2013 I WILL open odin and flash pit file like flashing pda for root !!
IM (D) variant

**Comment by almir77** [comment]
Mada12345:Please tell me what happens after! Is that experiment going to
work!?

**Comment by Mada12345** [comment]
romeo2013 iam afraid to do this bec.it will be brick the mobile im commented here to know is that steps right or it will brick the mobile :D

**Comment by almir77** [comment]
Ok dont try it...! Mabe TheWhisp will consider this case and fix unother
stable cmw for our jena.
