### ISSUE TITLE
Ram 378 !!

### ISSUE THREAD

**Issue by Mada12345** [TheWhisp/android_device_samsung_msm7x27a-common#173]
Thewhisp thank you for ur hard working .. But you make the ram 378 It isnt S4 !! Android system And bbm And google play took 300 mb Free For me 79 mb what i will do with that .. Pls Make The ram higher than this mini 2 Dosen't Have Sensors or Anything To make the ram like this You should make it 414 Or 398 Like gb .. and thank u

**Comment by arthur13** [comment]
youre right dude. please do it TheWhisp

**Comment by TheWhisp** [comment]
You wanted camera, now live with this. Usually there is 1 heap for video encoding/decoding and camera, with PMEM it is called PMEM_ADSP but with ION it is CAMERA_HEAP. Mini 2's old camera drivers still use PMEM and we cannot change that. It means those drivers can't use ION's CAMERA_HEAP. However, the ION-enabled kernel got adjusted to use CAMERA_HEAP for video decoding/encoding, and PMEM_ADSP was added for camera. This means that there are now 2 heaps instead of 1, which both are 18MB. I am planning to reduce the size required for camera (PMEM_ADSP)

**Comment by Mada12345** [comment]
Oki The camera 3.15 Mp I Use the camera from year to year what I mean That Make anything for Ram Kitkat The first Build Was 395 Mb ram when i will flash The Good Build That Have All fixes the ram will be 0 :S

**Comment by TheWhisp** [comment]
then use GB and stop whining. I couldn't care less about your problems.

**Comment by Mada12345** [comment]
My problems !! You Should See Our problems And solve it Don't tell use Gb !!!

**Comment by arthur13** [comment]
ok lets not argue couse thewhisp is developere he knows well

**Comment by Mada12345** [comment]
Oki i know that thewhisp know more informations about Android But he should care with this problem He make This page to see our opinions And problems about his work !!

**Comment by TheWhisp** [comment]
Are you capable reading? I already explained why there is 18MB less RAM. There is no way to fix it, you wanted camera? Here you go.

**Comment by Mada12345** [comment]
Can i Ask u question at 20-9 build Camera Working and ram 395 !!

**Comment by TheWhisp** [comment]
Custom ROMs are not suitable for you. Did you even read my first post in this discussion?

**Comment by Mada12345** [comment]
Yes I read it :S oki thewhisp thank u

**Comment by TheWhisp** [comment]
I managed to save 9MB, going further it wasn't possible to take pictures anymore

**Comment by arthur13** [comment]
ok thanks and what about swap ability???

**Comment by Mada12345** [comment]
Love U thewhisp :\* <3 But last thing Pls tell mee Pls man about repartition using odin Anyone Know how to do it Pls tell me Thanks :*

**Comment by george99** [comment]
Hey 
I solved problem with internal sd in our galaxy mini 2
You need 
-Odin3
-Drivers for S6500D

*.pit file : http://www4.zippyshare.com/v/12040816/file.html (you must unzipping)
How to install:
-connect phone in download mode
-put *.pit file to [PIT] in odin (Automatically selects the option to re-partition it should not be characterized.)
-press [Start] button and wait few minutes

NOTE! All files from the internal memory should not be deleted!

**Comment by TheWhisp** [comment]
I was solved ~ month ago.
