### ISSUE TITLE
Repartition

### ISSUE THREAD

**Issue by Mada12345** [TheWhisp/android_device_samsung_msm7x27a-common#178]
Hello everyone How are you !? I Have The same Problem The repartiton Please any one Can Tell Me How to do it Please Comment me . thanks :*

**Comment by TheWhisp** [comment]
nobody cares, stop spamming here :)

**Comment by arthur13** [comment]
your devise is nfc or non nfc??

**Comment by Mada12345** [comment]
non nfc (D) variant

**Comment by arthur13** [comment]
ok what odin do you use for it??

**Comment by Mada12345** [comment]
v1.85

**Comment by arthur13** [comment]
wait please i'll send you one with pit file

**Comment by Mada12345** [comment]
oki .. But how can i flash it ?

**Comment by arthur13** [comment]
https://drive.google.com/folderview?id=0B3LKFtMIkkk0OGdaaHJzQVloVms&usp=sharing

ok download this and try to repartition

**Comment by arthur13** [comment]
you will need stock android 2.3.6 last version

**Comment by Mada12345** [comment]
is it a joke i will brick my mobile

**Comment by arthur13** [comment]
no its not a joke i tried it myself and it worked
just select pit file  and stock rom and it will do repartition 

but use the odin that i sent to you or it wont work

**Comment by Mada12345** [comment]
Hey 
I solved problem with internal sd in our galaxy mini 2
You need 
-Odin3
-Drivers for S6500D

*.pit file : http://www4.zippyshare.com/v/12040816/file.html (you must unzipping)
How to install:
-connect phone in download mode
-put *.pit file to [PIT] in odin (Automatically selects the option to re-partition it should not be characterized.)
-press [Start] button and wait few minutes

NOTE! All files from the internal memory should not be deleted!

this steps are wrong

**Comment by arthur13** [comment]
this steps are right

**Comment by arthur13** [comment]
after this you will have boot loop 

then you should install CWM by TheWhisp and try the new rom

**Comment by Mada12345** [comment]
oki iwill do it without download stock rom that will be easy

**Comment by Mada12345** [comment]
oki i already installed cwm 6.0.4.5

**Comment by arthur13** [comment]
ok

**Comment by arthur13** [comment]
but how are you going to do that without stock rom???

**Comment by Mada12345** [comment]
I will open odin and flash pit file and check repartition and start

**Comment by arthur13** [comment]
im waiting keep me know

**Comment by Mada12345** [comment]
I Don't understand you !! :D

**Comment by arthur13** [comment]
report me after you did it

**Comment by Mada12345** [comment]
arthur13 the first thing the link not working second thing if i do this without stock it will be brick .. second after i put firmware in pda etc. iwill put pit file in pit and check repartiton ??

**Comment by arthur13** [comment]
try with stock rom

and you should have google account for the link

**Comment by arthur13** [comment]
after i put firmware in pda etc. iwill put pit file in pit and check repartiton ??

YES

**Comment by Mada12345** [comment]
i already have google acc. ... oki may i tell u one thing ??

**Comment by arthur13** [comment]
of course

**Comment by Mada12345** [comment]
please send me the link that i will download stock rom sorry but that is the first time to use odin and flash firmware :D

**Comment by arthur13** [comment]
its all right dude ill help you just wait

**Comment by Mada12345** [comment]
thank u thnak u for every thing ::*

**Comment by arthur13** [comment]
http://www.sammobile.com/firmwares/?
you should register here to download your rom

then search your devise and download

**Comment by Mada12345** [comment]
thank you man but but at xda galaxy mini 2 android develpement there is pit file but for cm10.1 only how can i use it

**Comment by arthur13** [comment]
can you give me the link??

**Comment by Mada12345** [comment]
of course man :D

**Comment by Mada12345** [comment]
http://forum.xda-developers.com/showthread.php?t=2525886

**Comment by arthur13** [comment]
this is it just download the rom,the pit file and tell me

**Comment by Mada12345** [comment]
OKi man i wil do it and tell u thanks arthur thanks for every thing :\* :)

**Comment by arthur13** [comment]
youre welcome

**Comment by arthur13** [comment]
just in case the steps

1.put pit file and rom in their places in odin at the same time.It will do repartition
2.after that bootloop
3.instal CWM via odin(the link      http://forum.xda-developers.com/showthread.php?t=2156194  )
4.install CM10/10.1/10.2/11 which you prefer
5.ENJOY  :)

**Comment by Mada12345** [comment]
u know what i afraid from stock rom downloading it and flash it and the pit file that i will download and repartiton im afraid to do this

**Comment by arthur13** [comment]
you neednt to afraid just do it like how i said

**Comment by Mada12345** [comment]
but what is that bootloop :D

**Comment by arthur13** [comment]
the stock rom wont run it will be showing just the boot animation

**Comment by arthur13** [comment]
i forgot to say that you should be in download mode to flash via odin

**Comment by Mada12345** [comment]
yeah iknow :D

**Comment by Mada12345** [comment]
You know what if i can repartition without stock rom what i mean that Put pit file and check repartiton and press start i will do it now But the Firmware It was veery difficult

**Comment by arthur13** [comment]
without pda it wont do anything

**Comment by Mada12345** [comment]
Pda Firmware file or pda root file !!?

**Comment by arthur13** [comment]
Firmware

**Comment by Mada12345** [comment]
BUT WHY cm10 and 10.1 we didn't Make Repartiton for them

**Comment by arthur13** [comment]
i dont know why

**Comment by arthur13** [comment]
i think its becouse of the new kernel

**Comment by Mada12345** [comment]
No hope that the whisp fix this problem :S

**Comment by arthur13** [comment]
he hasnt this problem thats why he wont fix this

**Comment by Mada12345** [comment]
Bec. he repartiotioned his phone but i know People that have mini 2 can't repartiton I know it today from u my bro But other people Didn't know

**Comment by arthur13** [comment]
we will tell them.lets solve your problem and see if our method is really hopeful and only then im going to write in forum that we have solved this problem

**Comment by Mada12345** [comment]
Thank u for everything And i will wait Thewhisp to fix this if he dosen't fixit iwll repartiton

**Comment by arthur13** [comment]
i think he will never fix this
i opened issue in this list and he closed it 
he says he doesnt have this problem and he cant fix it

**Comment by Mada12345** [comment]
Oh my god .. Look Lets open Thread in xdato put this steps

**Comment by arthur13** [comment]
can you???

**Comment by Mada12345** [comment]
May be :D

**Comment by arthur13** [comment]
ok i wiil try too

**Comment by arthur13** [comment]
ok i have already made the thread

**Comment by Mada12345** [comment]
Good man ... have you got bbm !?

**Comment by arthur13** [comment]
what is it??

**Comment by Mada12345** [comment]
Black berry mesenger

**Comment by arthur13** [comment]
no

**Comment by Mada12345** [comment]
Or facebook

**Comment by arthur13** [comment]
i have got only gmail and mail accounts

**Comment by Mada12345** [comment]
Oki if you have yahoo or hotmail send it to me

**Comment by arthur13** [comment]
ok i have facebook account
my name is hovo gasparyan

**Comment by Mada12345** [comment]
arthur One Replay In your thread or you Idon't know but he Wrote that i will put pit file only Without stock rom And press start Then wait for a while !! ... what is your opinion about that !!

**Comment by arthur13** [comment]
i have already tried that and i failed it 

it worked only with pda firmware

**Comment by Mada12345** [comment]
Any firmware !!?

**Comment by arthur13** [comment]
only stock

**Comment by Mada12345** [comment]
Sorry one minute They are the Same or not !!

**Comment by arthur13** [comment]
what is the same

**Comment by Mada12345** [comment]
Stockrom and firmware :D

**Comment by arthur13** [comment]
yes they are same

**Comment by arthur13** [comment]
mada you tried my method or not

**Comment by Mada12345** [comment]
oki but if the mobile brick from me how can i fix it !? :D

**Comment by arthur13** [comment]
ok i wiil try to make a video how to do it

**Comment by Mada12345** [comment]
i will do it in my holiday in the next week Don't worry i ask you to get all the informations about the repartiton

**Comment by Mada12345** [comment]
Okiii :D

**Comment by arthur13** [comment]
the second method works too

**Comment by Mada12345** [comment]
Which one tht without stockrom

**Comment by arthur13** [comment]
yes

**Comment by Mada12345** [comment]
yeaaaah :D Iam very happy :D

**Comment by arthur13** [comment]
im glade

**Comment by Mada12345** [comment]
Yes man .. But what steps !?? :D :D :D

**Comment by arthur13** [comment]
http://forum.xda-developers.com/showpost.php?p=48905684&postcount=12

here they are

**Comment by Mada12345** [comment]
Goood maaaaaaaaaaan <3 <3

**Comment by arthur13** [comment]
you did it???

**Comment by Mada12345** [comment]
No i Amgoing to do it but after study  :D

**Comment by arthur13** [comment]
ok

**Comment by Mada12345** [comment]
I told these steps to my friends that have galaxy mini 2 and all thanked u

**Comment by arthur13** [comment]
youre welcome

**Comment by arthur13** [comment]
mada im sorry for this question but how old are you????

**Comment by Mada12345** [comment]
No don't tell sory :D im 16 Years old

**Comment by arthur13** [comment]
me too

glade to know you

**Comment by Mada12345** [comment]
me too Im very happy to know a genious man like you :D

**Comment by arthur13** [comment]
i think this is the start of our frandship

**Comment by Mada12345** [comment]
Yes I hope to be best friends <3

**Comment by arthur13** [comment]
what nationality are you

**Comment by Mada12345** [comment]
Im from egypt and you

**Comment by arthur13** [comment]
from armenia

**Comment by Mada12345** [comment]
Nice to meeet you ;)

**Comment by Mada12345** [comment]
Are you (D) variant !?

**Comment by arthur13** [comment]
yes

**Comment by Mada12345** [comment]
Okeeee :D

**Comment by arthur13** [comment]
marry christmas

**Comment by Mada12345** [comment]
Merry christmas <3 To u too bro.
