### ISSUE TITLE
Status bar and quick settings

### ISSUE THREAD

**Issue by ghost** [TheWhisp/android_device_samsung_msm7x27a-common#18]
Sometimes when pulling down the status bar it doesn't show the quick settings shortcut in the top right of the screen.

**Comment by TheWhisp** [comment]
I have never experienced such issue

**Comment by ghost** [comment]
Why close the issue then when you haven't experienced it? I'm telling you there's a bug and I explained so you can fix it; not to say there's nothing to fix.

**Comment by TheWhisp** [comment]
there is no such bug. I have used this ROM since early development begin in February. Never had such an issue.

**Comment by ghost** [comment]
Well it's happening to me, it could be something with the 18/7 build :S I'm sure something wrong?

**Comment by ghost** [comment]
![2013-08-17 18 05 26](https://f.cloud.github.com/assets/5247737/981274/ee033384-0756-11e3-9c1d-2ed08cd136a1.png)

**Comment by TheWhisp** [comment]
Even if there is such a bug, it's clearly on CM side. Try disabling toggles.

**Comment by ghost** [comment]
![2013-08-17 18 13 54](https://f.cloud.github.com/assets/5247737/981288/11278ca6-0758-11e3-87fd-e3fc2facd44a.png)

**Comment by ghost** [comment]
I had to reboot my phone for the shortcut to show up.

**Comment by arthurvigen** [comment]
maybe you had instaled any program that made your device be buggy
