### ISSUE TITLE
whitescreen and camcorder not work in CM11 20131231

### ISSUE THREAD

**Issue by hasan-bisri** [TheWhisp/android_device_samsung_msm7x27a-common#180]
I am happy and I am proud to use thewhisp work, I also support the hard work so that I can feel thewhisp jellybean and kitkat on my phone. stay a little longer resolved white screen, now in the build CM11 20,131,231 white screen stay on while charging online and camcorder does not work. thanks. I use samsung GT-S6500D

**Comment by TheWhisp** [comment]
are you blind?

**Comment by hasan-bisri** [comment]
I'm not blind!
Pada 2 Jan 2014 19.54, "Dāvis Mālnieks" notifications@github.com menulis:

**Comment by TheWhisp** [comment]
then why in the hell do you create 2 issues that already exist!?

**Comment by hasan-bisri** [comment]
because I only send log bugs that occur in my phone
Pada 2 Jan 2014 21.26, "Dāvis Mālnieks" notifications@github.com menulis:

**Comment by TheWhisp** [comment]
do you even understand what you just wrote?

**Comment by hasan-bisri** [comment]
yes I understand
Pada 2 Jan 2014 21.34, "Dāvis Mālnieks" notifications@github.com menulis:
