### ISSUE TITLE
[CM-10.1] After playing music cannot enter deep sleep. 

### ISSUE THREAD

**Issue by SilicaAnimus** [TheWhisp/android_device_samsung_msm7x27a-common#182]
After playing music from stock (Apollo) player phone can't enter into deep sleep mode. This seems to happen only after playing several files, possibly related to manually changing and pausing them. Also it's occuring only with headset, at least for me. 

Disabling LPA i build.prop removed problem, so i think that he lays somewhere in LPA subsystem. 

Logs after playing with blocking deep sleep effect:
https://dl.dropboxusercontent.com/u/5762822/archives/2014-01-03.7z

Device: GT-S6500 (NFC).
ROM: cm-10.1-20131227-UNOFFICIAL-jenad

EDIT:\

It is also happening only when playing MP3 music, FLAC`s aren't affected, propably because this format is not handled by LPA.

**Comment by TheWhisp** [comment]
I suppose if this would've been device-specific bug, it would affect all ROMs
