### ISSUE TITLE
CM11 option to swap PROBLEM !!!

### ISSUE THREAD

**Issue by george99** [TheWhisp/android_device_samsung_msm7x27a-common#183]
Hi when i use the option to swap it's not mounting sdcard0 and sdcard1 .

**Comment by Mada12345** [comment]
Repartition it :)

**Comment by george99** [comment]
I've tried and nothing.

Sorry for my bad english. :)

**Comment by Mada12345** [comment]
No problem .. I think that to do it again

**Comment by TheWhisp** [comment]
This is an addition feature.
