### ISSUE TITLE
Lock screen numbers don't fit.

### ISSUE THREAD

**Issue by digitz** [TheWhisp/android_device_samsung_msm7x27a-common#185]
![unnamed](https://f.cloud.github.com/assets/6322856/1898895/f8e87cda-7c2e-11e3-8cb9-e57b13865155.png)

**Comment by Boerde** [comment]
Can confirm.
Upgraded recently from Version 10.2  -> numbers looked fine
to Version 11 -> numbers in lockscreen are cut in half, so I only see the top half of every number
