### ISSUE TITLE
brightness

### ISSUE THREAD

**Issue by Mada12345** [TheWhisp/android_device_samsung_msm7x27a-common#186]
Auto Brightness In cm11 Build 3-1-2014 Doesn't work but all is fine Thats good Build and thank you <3

**Comment by TheWhisp** [comment]
no issues for me

**Comment by arthur13** [comment]
mada you finaly updated your devise

**Comment by Mada12345** [comment]
Yeah my bro. I repartitioned it and Installed Latest Build With gapps and work With kitkat <3 Thank U very much Thewhisp <3 And arthur Thank u bec. u help me to flash a Kitkat and any rom i want <3
