### ISSUE TITLE
Not a bug, but a Request for cm 10.2!

### ISSUE THREAD

**Issue by ihasdivui** [TheWhisp/android_device_samsung_msm7x27a-common#187]
TheWhisp, can you please do a JENA version because if I use a JENAD version my GT-S6500 Bootloops. So, if you would do a jena version of cm 10.2, you would help many people in Germany and Austria! That would be very nice from you.
Thanks, ThejenaROMtester.

**Comment by Mada12345** [comment]
bootloop at cm10.2, You would to repartiton it Maan ;)

**Comment by ihasdivui** [comment]
Yea, but theres the Problem! I dont like to Repartition it, because if I do it, all the Datas would be deleted from sdcard0, right?
And no, I don't have a PC now.

**Comment by ihasdivui** [comment]
And if I use JENA! not JENAD, It must'nt be repartioned!

**Comment by Mada12345** [comment]
No my bro. Repartition Format system Not sdcard0,all ur data will be not Deleted .. And Tell me What Variant Do you work When U use GB S6500D Or S6500!?

**Comment by ihasdivui** [comment]
I am using S6500, thos is the jena version, and if TheWhisp would make a jena Version, I wont need to repartition my S6500! If you understand that. I dont have a PC right now! I cant repartition my sgm2!

**Comment by ItachiSan** [comment]
@ThejenaROMtester, there are few points you should consider:
1. There's no pit file for S6500, so no repartitioning is avaible.
2. I've a S6500 too and I had no problem when installing the ROM.
3. A logcat+kmsg would be fine to debug the error, if it's a ROM error.
4. As said on **xda-developers**
_no logcat -> no errors_

That's all folks

**Comment by ihasdivui** [comment]
But why the cm 10.1 JENA!! worked? So I think my sgm2 is a little piece of Problems... And how do I a Logcat (It wasnt a Bootloop, it didnt start, pnly the Boot Animation was seen. A Bootloop is, as I know, If the ROM starts and after a few seconds or minutes it restarts. So heres the Problem! I cant use Logcat...

**Comment by ihasdivui** [comment]
In Summer i'll buy a Samsung Galaxy S4 mini, so this here doesn't matter anymore... Closed.
