### ISSUE TITLE
google maps

### ISSUE THREAD

**Issue by arthurvigen** [TheWhisp/android_device_samsung_msm7x27a-common#19]
it is buggy too

Device:SGM2

**Comment by bqubique** [comment]
It is working greatly on Galaxy Ace Plus with Google Maps 6.9  , so I think it only happens on latest version of Google Maps

**Comment by ghost** [comment]
Happens to me on my GT-6500D

**Comment by arthurvigen** [comment]
I dont think so becouse the same bug is in flash player.

Who wants to make sure instal adobe flash player for ICS+,instal swf player,download swf game and you will see that its not working

**Comment by leggiero** [comment]
Same with the GT-6500

**Comment by arthur13** [comment]
will it be fixed in cm10 new build?

**Comment by ghost** [comment]
Happens in google maps navigation too. (Jena)

**Comment by arthur13** [comment]
are there any changes?

**Comment by TheWhisp** [comment]
There is no solution, either:

1) Google Apps problem ( a lot of devices have this bug, even some old high-end devices )
2) ROM uses too old APIs, but on the other hand, CM10 has official Adreno libs and CAF 3.0 kernel.

So there really is not solution and I don't know what's the cause of this.

**Comment by arthur13** [comment]
ok

**Comment by TheWhisp** [comment]
Fixed
