### ISSUE TITLE
Camera is not working

### ISSUE THREAD

**Issue by mindwars** [TheWhisp/android_device_samsung_msm7x27a-common#190]
I've installed cm11 nightly 03/01/2014 but camera is not working. How could it be? Is there any solution? 

Note: Logcat is  here: http://justpaste.it/e1rv

**Comment by TheWhisp** [comment]
Working fine for me. Is the error you're getting similar to "curve hands"?

**Comment by Mada12345** [comment]
Camera working fine for me Too The Camcorder Doesn't work Not Caamera :)
