### ISSUE TITLE
Zram 11-1-2014

### ISSUE THREAD

**Issue by Mada12345** [TheWhisp/android_device_samsung_msm7x27a-common#194]
HEY bro. How are you !? Ihope to be in a good health but I want to ask u one question Where is Zram In latest build Cm11 !?

**Comment by TheWhisp** [comment]
it's enabled by default and is set to 64MB see: https://github.com/TheWhisp/android_device_samsung_msm7x27a-common/commit/6395af9bdbbd2e08695846c590144028c4825b68

**Comment by Mada12345** [comment]
okie bro. ;)
