### ISSUE TITLE
480p Playback

### ISSUE THREAD

**Issue by ItachiSan** [TheWhisp/android_device_samsung_msm7x27a-common#196]
On stock, video playback of online videos of 854x480 resolution was fine; actually, the maximum playback resolution is 640x360 (I suppose, for sure this one is working).
This issue is written down to track progress about it.

**Comment by ItachiSan** [comment]
Found that
_/system/etc/01_qcomm_omx.cfg_
allows to load specific OMX.
Something about it: https://groups.google.com/forum/#!topic/android-porting/2-fRrkunBWo
Actually, on **stock ROM** there's such a file.
We could try use proprietary stock OMX, or we can patch stagefright in order to use them, as was done for ARMv6 devices (MSM7x27)

**Comment by TheWhisp** [comment]
Why would I downgrade from official JB OMX libs that use ION to GB OMX libs? Online playback works on 4.3.x, but is broken on KK.

**Comment by ItachiSan** [comment]
About KK: OMX problem or webcore related (which one do you suppose)?
About downgrading: never meant it fully (it is a possibility though); actually it would the best to
enable 480p video playback with JB OMX libs (as you said, they use ION).

**Comment by TheWhisp** [comment]
I suppose you have no idea what you're talking about.

**Comment by ItachiSan** [comment]
Actually, I have. The fact is:
- On stock can play videos up to 854x480 with OMX -> no need for S/W decoder-based player
- On CM -> 854x480 videos cannot be played with OMX decoder -> needed a S/W decoder

The videos have this streams:

**Video** 
- codec H.264
- frame rate 25 fps
- resolution 854x480
- bitrate 1Mbit/s max (not sure at 100%)

**Audio**
- codec: AAC
- bitrate 124 kb/s
- Channels 44.1 KHz
- Stereo output

If I'm not wrong, _MS7227a_ chipset are able to decode a _FWVGA video_ (854x480 resolution) with maximum 30 fps and max bitrate 2 Mbit/s, as on stock.
My actual question is:
_Why any player, considered all this stuff, just not play them (without S/W decoder) as it should?_

I know, I'm kinda fussy and bothering, I'm sorry for this.

**Comment by TheWhisp** [comment]
because msm7x27a does not officially support 4.1+
I can play mpeg4 FWVGA videos, h264 doesn't work because OMX_StoreMetaDataInBuffers fails

**Comment by ItachiSan** [comment]
Oke, thanks, that's the answer I was looking for. :+1:
