### ISSUE TITLE
Charger stuck at 99% [CM-10.1]

### ISSUE THREAD

**Issue by ItachiSan** [TheWhisp/android_device_samsung_msm7x27a-common#197]
Actually, in CM-10.1, the phone does not recognise to be charger.
Example:
- turn it off
- charge it for a whole night
- it will be stuck at 'almost charged' screen

When online, it stays stuck to 99% in battery stats.

**Comment by TheWhisp** [comment]
That's just the way Samsung has implemented it, and it actually is correct. When you unplug the charger, it really isn't 100% anymore.

**Comment by ItachiSan** [comment]
Was malformatted the text I wrote (now corrected); I mean, there's no chance to have 100% battery charged as for now. Is it correct?
At least in _charger_ the actual battery value could be set to "real_battery_charge + 1" so the battery can be marked as charged, even if it isn't.

**Comment by TheWhisp** [comment]
It always charges to 100% on my device, then I see "Fully charged"

**Comment by ItachiSan** [comment]
Sincerly, I never saw it in a few days...
Will try to be more patient.
