### ISSUE TITLE
CWM Recovery not mount the sdcard0.

### ISSUE THREAD

**Issue by Brunever123** [TheWhisp/android_device_samsung_msm7x27a-common#198]
The problem is with the latest update of CWM (6.0.4.5) does not mount the sdcard0. 

I installed the CWM 6.0.3.3-taking b2, only install through CWM already said. Just tell me if and installed correctly, Please

**Comment by ihasdivui** [comment]
Why you closed that without an answer, @TheWhisp?

**Comment by TheWhisp** [comment]
read the labels perhaps?
