### ISSUE TITLE
cm11 Sony Xperia Z yuga sound glitch

### ISSUE THREAD

**Issue by nasibi** [TheWhisp/android_device_samsung_msm7x27a-common#199]
I flashed the cm-11-20140116-NIGHTLY-yuga.zip on my Xperia Z. Everything is working good for me except this sound glitch. Whenever I play videos or music, I hear this ''bzzzz'' sound glitch in the middle. Can anyone please fix this issue?

**Comment by TheWhisp** [comment]
What does this got to do with Mini 2?
