### ISSUE TITLE
cm11 Sony Xperia Z yuga GPS bug

### ISSUE THREAD

**Issue by nasibi** [TheWhisp/android_device_samsung_msm7x27a-common#200]
i flashed the cm-11-20140116-NIGHTLY-yuga.zip on my Xperia Z. The GPS tile in my quick settings menu doesn't function properly. Sometimes it works, sometimes it doesn't and I have to restart the phone for it to work. Please resolve it.

**Comment by TheWhisp** [comment]
what is this got to do with Mini 2?
