### ISSUE TITLE
[CM-10/10.1] Wifi Access point not working

### ISSUE THREAD

**Issue by ItachiSan** [TheWhisp/android_device_samsung_msm7x27a-common#204]
**What should happen**
After having activated the Wifi AP, I should be able to connect to it with any Wifi-capable devices and surf the Internet.
**What happens**
When trying to surf the Internet, the devices connected to the Wifi AP seems to be not connected to the Internet.
**Suppositions**
Considering this line:
_...
D/Tethering(  429): notifying tethered with iface =null
..._
it seems that Android cannot, as for now, detect mobile data iface.
**Ideas**
If I'm not wrong, I'll fix this in a while, just have to add some build define lines to configs.
**Full logcat**
Here: https://gist.github.com/ItachiSan/8581818

**Comment by ItachiSan** [comment]
Confirmed to not be working also on CM-10

**Comment by ItachiSan** [comment]
Just made a test from my old Galaxy Gio (with CM-10.1, working Wifi tethering).
I compared the two logcats of tethering and on both devices the tethering iface (for _jena(d)_ **wlan0**) is thetered correctly, instead the mobile data one is not (on _gio_ is **pdp0**, here it should be the same but it isn't used)
I attach also a logcat of working Wifi tethering:
https://gist.github.com/ItachiSan/8683883

**Comment by ItachiSan** [comment]
I've kinda an idea of how to fix...

**Comment by ItachiSan** [comment]
Wrong idea. I took another logcat today and I saw that _hostapd_ starts up properly...
The problem is in the framework that does not detect that _hostapd_ has started (or similar).

**Comment by TheWhisp** [comment]
I removed 'BOARD_MOBILEDATA_INTERFACE_NAME := "pdp0"' from the config, I thought it was obsolete. Maybe you can check if it is doing anything

**Comment by ItachiSan** [comment]
I thought it too, already tried to use it; I found that the build flag related to this change was removed...
Maybe it works anyways. Will re-try later (now I'm fighting with patches for white screen)

**Comment by ItachiSan** [comment]
Enabled the flag
**BOARD_MOBILEDATA_INTERFACE_NAME := "pdp0"**
and also some overlay in msm7xa config. Will see if something will change.

**Comment by ItachiSan** [comment]
Man, is normal that I've a stacktrace error with _get_macaddrs_?

https://gist.github.com/ItachiSan/8774880

**Comment by ItachiSan** [comment]
Now Wifi tethering works.
It's marked to tether with **_pdp1**_ instead of exprected **_pdp0**_.
Will track down to the correct commit I did and then make a patch. ;)

**Comment by TheWhisp** [comment]
not it is not normal to have that crash with get_macaddrs, I blindly copied it from cm-10.2, it probably needs some minor changes to work on cm-10
It seemed to work as expected when I last tried cm-10, though

**Comment by ItachiSan** [comment]
For the moment, I created pull request #211 to fix Wifi tethering. ;)

**Comment by TheWhisp** [comment]
can I mark this as fixed?

**Comment by ItachiSan** [comment]
Apart the **get_macaddrs** stacktrace, now Wifi AP works flawlessy.
Depends if you want to keep it open for **get_macaddrs** or not, your choice ;)
