### ISSUE TITLE
External SD not working on CM 11 jenad

### ISSUE THREAD

**Issue by portena** [TheWhisp/android_device_samsung_msm7x27a-common#207]
I have just installed your release for the Galaxy Mini 2 (GT-6500D), but I cannot not access the SD with any app like bluetooth file manager, the native file manager that comes with the ROM, gallery or photos app. I could install every app that my google account wanted to recover from the previous CM version I had. I'm spanish, so please don't look on my mistakes. Thanks.

**Comment by ekafjr** [comment]
before  flash cm 11  flash pit file first

**Comment by portena** [comment]
All right, there ain't a working pit file for GT-S6500D. They said trying to flash it whit ODIN: secure check failed 0x95

**Comment by TheWhisp** [comment]
I'm sorry. but are you really that stupid? Can't you see this has been posted like million times already?
