### ISSUE TITLE
many games cant be played.

### ISSUE THREAD

**Issue by ikkialex** [TheWhisp/android_device_samsung_msm7x27a-common#21]
I don't know how to explain but the game just cant be played. for example "Spartan wars empire of honor and maple story live" The game just start and show the intro screen then closed and exit to the main screen. I guess it's not about flash player problem or I am wrong? please have a check on that.

**Comment by ghost** [comment]
I don't think this is about flash player, this is because this device is a low end device (~800 MHz processor, ~512MB RAM) It is not capable of gaming, even on stock 2.3.6 ROM.

**Comment by TheWhisp** [comment]
as I already posted on XDA thread, some other msm7x27a devices have this problem. That is a bug most likely in CM itself.
