### ISSUE TITLE
[CM 10.1] GPS is kinda unusable

### ISSUE THREAD

**Issue by ItachiSan** [TheWhisp/android_device_samsung_msm7x27a-common#217]
With GMaps, while travelling, location is lost 99% of the time.
Actually, all the needed libs are built...
So my question is _why this happens_.

**How to reproduce**
1. Decide to go somewhere.
2. Set destination on GMaps, use the navigator.
3. You'll have an awful experience **_yippie**_

**Comment by TheWhisp** [comment]
Just because it's a Google app doesn't mean it is perfect. I have never had any problems with GPS... Mini 2 just cannot handle Maps 7.x app, it's really slow.

**Comment by ItachiSan** [comment]
Oke mate, thanks :)
Suggestion for navigator? ;P

**Comment by ItachiSan** [comment]
Waze is fantastic, I discovered.
I suggest it.
No _moar_ comments ;P
