### ISSUE TITLE
CM11 Minecraft PE not working

### ISSUE THREAD

**Issue by S6500D** [TheWhisp/android_device_samsung_msm7x27a-common#221]
Hi i have S6500D and i am running cm11 on it . I've tried to play minecraft pe version 0.8.0 , 0.8.1 and etc . But when i open the game it shows black screen and it freezes.

Sorry for my bad english.

**Comment by ihasdivui** [comment]
Minecraft PE currently does not support Android KitKat 4.4 correctly. Hopefully, in future there will be support for the new Android!
