### ISSUE TITLE
Cannot reach SIM contacts

### ISSUE THREAD

**Issue by hsaykin33** [TheWhisp/android_device_samsung_msm7x27a-common#229]
I have GT-S6500D 4.4.2 installed. It seems that rom does not recognize sim contacts.

**Comment by TheWhisp** [comment]
Just added and imported a contact to/from SIM card, crashed RIL, but it worked.

**Comment by hsaykin33** [comment]
I have contacts in my sim cart but when i try to import them via "Contacts" it says "no contacts on sim cart(or something like that)" . However i can reach my contacts when i put my sim to another phones.

**Comment by hsaykin33** [comment]
Bdw what is RIL? Do I need an another application to import my sim contacts?
