### ISSUE TITLE
CM10 no SIM contacts, no ext sd card

### ISSUE THREAD

**Issue by razvynator** [TheWhisp/android_device_samsung_msm7x27a-common#231]
every CM10+ i falshed in my s7500 has 2 problems... i cannot see my sim contacts.. with no app, even if i backup contacts on ext card wont work, cuz phone wont see ext card when i enter file browser, but when i enter music app i can see and listen to my music from ext card. what is the problem here? is it my phone or it happens on dailly basis?

**Comment by ItachiSan** [comment]
For opening your external SD card, use the bookmarks button.
For SIM contacts, they worked for me.

**Comment by TheWhisp** [comment]
This again? Read the other zillion issues with the same theme
