### ISSUE TITLE
ROMDUMP MODE

### ISSUE THREAD

**Issue by ghilson23** [TheWhisp/android_device_samsung_msm7x27a-common#232]
![1799169_10203087368162501_1894190889_o](https://f.cloud.github.com/assets/6963159/2429820/d8fb8b0c-ac9d-11e3-8008-740945b891f7.jpg)
![1921167_10203087368402507_923205514_o](https://f.cloud.github.com/assets/6963159/2429821/d8fca7ee-ac9d-11e3-95c5-18226a0040f3.jpg)

trying to flash using Odin but it wont get out of this screen. nothings happen. pls help.

pressing vol + home screen and power button doesnt work to bring it on download mode. but odin can detect it.

**Comment by TheWhisp** [comment]
none of my ROMs are odin flashable. This is not a help desk if you haven't noticed
