### ISSUE TITLE
ring problem in jena

### ISSUE THREAD

**Issue by MarciPain** [TheWhisp/android_device_samsung_msm7x27a-common#24]
After installed cm 10.1 on jena,  all ringtones are silent. (i installed the rom twice)

**Comment by bqubique** [comment]
Phone ringtones or ,VOip ringtones ,like whatsapp ,etc.?

**Comment by TheWhisp** [comment]
I haven't experienced such problems. Make sure your ringtones aren't set as 'silent' and you use a valid ringtone

**Comment by MarciPain** [comment]
INeither the  internal  and the custom ringtones do not work.
not muted telephone, the factory firmware they work.

**Comment by MarciPain** [comment]
Why close?
Create video from this problem?
