### ISSUE TITLE
2 bugs

### ISSUE THREAD

**Issue by IITap** [TheWhisp/android_device_samsung_msm7x27a-common#241]
When calling someone you see in background there are homescreen options and also when removing google search bar then I cant remove shortcuts on homescreen. Please fix it. Thanks.

**Comment by IITap** [comment]
One more bug. When im on app drawer and when i tap the option (lower left) button I can see homescreen options behind the appdrawer apps. fix this please.

**Comment by TheWhisp** [comment]
I'm not working on this device anymore...
