### ISSUE TITLE
White screen after phone lock

### ISSUE THREAD

**Issue by shoro** [TheWhisp/android_device_samsung_msm7x27a-common#246]
If I lock my phone or it locks himself, when I try to unlock it gives me a brite white screen, the touch seems to work but I can't see what I'm doing on the screen because of that white screen.

Only if I pull out the battery I can use my phone but until next lock.

Any ideas???

CW11 - Samsung Galaxy Mini 2

**Comment by lozohcum** [comment]
Looks like framebuffer/surfaceflinger is broken.

Did you check the output of adb logcat *:E ?
