### ISSUE TITLE
Patch in frameworks_native not successfully applied

### ISSUE THREAD

**Issue by eyedeekay** [TheWhisp/android_device_samsung_msm7x27a-common#252]
When I attempt to apply the 0001-Revert-sf-Set-view-frame-of-each-display-using-binde.patch, I get the following error:

Falling back to patching base and 3-way merge...
Auto-merging services/surfaceflinger/SurfaceFlinger.cpp
CONFLICT (content): Merge conflict in services/surfaceflinger/SurfaceFlinger.cpp
Auto-merging services/surfaceflinger/Android.mk
CONFLICT (content): Merge conflict in services/surfaceflinger/Android.mk
Failed to merge in the changes.
Patch failed at 0001 Revert "sf: Set view frame of each display using binder"
The copy of the patch that failed is found in:
   /home/dyngar-f/android/android/frameworks/native/.git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

I have attempted to reproduce the changes made by the patch but haven't built successfully with them yet.

**Comment by TheWhisp** [comment]
the problem is that the source has been changed since the patch was made, hence the merge errors. Re-do the changes manually (the conflicting part), git add, and then git am --continue
