### ISSUE TITLE
http://goo.im/devs/thewhisp/jena-cm10.1 not working 

### ISSUE THREAD

**Issue by lghinet** [TheWhisp/android_device_samsung_msm7x27a-common#261]
http://goo.im/devs/thewhisp/jena-cm10.1 not working 
http://goo.im is down 
do you have any alternative, for the latest stable 10.1 for s2 mini 
 thanks

**Comment by ghost** [comment]
Looks like [goo.im was put for sale some time ago](https://bitcointalk.org/index.php?topic=1167838.0), so I wouldn't count on it ever going up again.

After waddling through tons of broken links, I found this [**Jena CM 10.1 ROM** on the XDA dev forum](http://forum.xda-developers.com/devdb/project/?id=5060#downloads), which works at this moment of writing. (Well, the link works at least. Haven't tried the ROM yet.)
