### ISSUE TITLE
WI-FI

### ISSUE THREAD

**Issue by arthur13** [TheWhisp/android_device_samsung_msm7x27a-common#27]
its not working.Stucks at turning on

**Comment by TheWhisp** [comment]
I have never had such problem

**Comment by arthur13** [comment]
so i have .wat are you going to do fix it or just close it

**Comment by TheWhisp** [comment]
I don't care what you have. If it's working for me then it means it's working. Isn't it weird that no-one else has said anything about it despite the latest build being released over month ago?

**Comment by arthur13** [comment]
im glade for your respects but what about mine?Wy mine isnt working ,mine is special?

**Comment by jinxu93** [comment]
Hi I'm having the same Wi-Fi problem too. My home wifi is secured with WEP. The Wifi just won't connect. It just remains turned on without any connection
