### ISSUE TITLE
WiFi contantly loosing connection. 

### ISSUE THREAD

**Issue by SilicaAnimus** [TheWhisp/android_device_samsung_msm7x27a-common#30]
After upgrading Cm10.1 to today build WiFi constantly reconnecting.

Device: GT-S6500.

Update proceeded without data wiping, only cache and Dalvik-cache was wiped.

**Comment by TheWhisp** [comment]
the new Wi-Fi driver is still WIP

**Comment by SilicaAnimus** [comment]
Understood. So I will downgrade CM to previous build.

**Comment by TheWhisp** [comment]
Try taking bdata.SD31.bin from old build (/system/etc/wifi/), rename it to bdata.bin and push it in new CM10.1 build into /system/etc/firmware/ath6k/AR6003/hw2.1.1/, reboot and test it then.

**Comment by SilicaAnimus** [comment]
In old CM i found bdata.SD31.bin in system\wifi\ath6k\AR6003\hw2.1.1 , this is it?

**Comment by TheWhisp** [comment]
yes

edit: the problem is with sleep. When the device enters sleep mode Wi-Fi loses connection. I have compiled 2 boot images with 2 different workarounds for this problem:

1) https://www.dropbox.com/s/d02ptg5rnlh4fj6/boot.img-wmi-workaround.zip (WMI workaround)
2) https://www.dropbox.com/s/pfkgq4aslovdze4/boot.img-sysfs-workaround.zip (SYSFS workaround)

Could you try these boot images and tell me on which one Wi-Fi performs better?

**Comment by SilicaAnimus** [comment]
I can't flash them. How to install them?

**Comment by ghost** [comment]
I got the same issue, I upgraded to today's build without clearing cache nor data. I just did a nandroid just incase. At first boot the device was laggy, so I had to reboot again. Now it's much better but the Wi-Fi icon in the status bar keeps turning gray at times and the disconnects, also the signal never gets past 1 bar.

**Comment by TheWhisp** [comment]
The signal does get past 1 bar. You can replace boot.img in .zip file with the one I uploaded, and then flash it.

**Comment by SilicaAnimus** [comment]
OK, I try it.

**Comment by TheWhisp** [comment]
After you try both boot.img, write here which one was better. One of them has to fix that issue.

**Comment by SilicaAnimus** [comment]
Both aren't working.

**Comment by ghost** [comment]
Both aren't working.

**Comment by SilicaAnimus** [comment]
Any progress with reparing WiFi? I want to help test patches, but I can't
wait long, because my phone is not too usefull for me witchout WiFi...

**Comment by ghost** [comment]
You can flash 20130718 build until there's a fix or a new build released.

**Comment by SilicaAnimus** [comment]
I know it, but i'm temporary staying on 18.08 build, to help test fixes. 
Unfortunately, I can't doing this for long.

**Comment by ghost** [comment]
Any fix yet?

**Comment by SilicaAnimus** [comment]
We must be patient. I think reparing this require time, also TheWhisph is
not a coding mashine, they can have not time to work...

For this moment, I returned to previous build & waiting for build with fix.

**Comment by jsgage** [comment]
tried both images on gt-7500 before i realized they were for gt-s6500 ow well both didnt work ,got boot logo then white screen where bootanim should be .. unable connect via adb

**Comment by TheWhisp** [comment]
Sorry, guys. I made a mistake. The reason why none of those 2 "patches" worked, was because I uploaded a kernel (boot.img) but the actual fix was done in the WiFi module itself (ath6kl.ko and cfg80211.ko) I'll try to upload the modules later this week ;)

**Comment by SilicaAnimus** [comment]
Nothing was happened, but basing on this I suppose that You have very 
successful holidays. :>

**Comment by TheWhisp** [comment]
Try this: https://www.dropbox.com/s/y4cyf7zytrrtyqg/ath6kl-cfg80211-sysfs.zip

Push both .ko files in /system/lib/modules and reboot

**Comment by SilicaAnimus** [comment]
Still nothing.

**Comment by scheibenwischer** [comment]
Looks good. No more reconnections. Copied 150 mb to smb -> passed (sleep mode sometimes activ). Thanks alot!

**Comment by scheibenwischer** [comment]
My Mobile rebooted 2 times in sleep mode. Try to catch it in a logcat if it reboots again.

**Comment by ghost** [comment]
Won't let me turn Wi-Fi on.

**Comment by TheWhisp** [comment]
@scheibenwischer Good. I'll try to fix the sleep bug and upload another patch.

Btw., those modules should fix "keep wifi on while sleeping" option in Wi-Fi settings

**Comment by scheibenwischer** [comment]
No reboot if USB Cable is connected. After disconnecting from USB i got a reboot after a few minutes again.

**Comment by TheWhisp** [comment]
Try: https://www.dropbox.com/s/ccvkzu0kjw406ie/wifi_patch_2-libhardware_legacy%2Bmodules.zip

You'll also need: https://www.dropbox.com/s/foiov7qg27x2oxg/boot.img-wififix.zip so the Wi-Fi modules can load

**Comment by scheibenwischer** [comment]
wifi active in sleepmode but problems with reboots.
pushed kmsg to thewhisp...

**Comment by ghost** [comment]
Wi-Fi isn't working in sleepmode for me.

**Comment by ghost** [comment]
http://pastebin.com/RJ5euQ6x

**Comment by iformas** [comment]
i get the same issue :C , please fix it :)

**Comment by TheWhisp** [comment]
the problem is that MMC card is removed when device goes to suspend. This means that the Wi-Fi turns off. I have to find a way to keep MMC on while suspend.

**Comment by TheWhisp** [comment]
Workaround: Settings > Wi-Fi > Advanced > Untick "Wi-Fi optimization"

**Comment by ghost** [comment]
With the files you provided or with the original ZIP?

**Comment by TheWhisp** [comment]
don't know, I am on a newer build. You can try it anyway.

**Comment by SilicaAnimus** [comment]
I remember that on latest build this workaround wasn't working. It was my
first attempt to fix WiFi failure when I observed it.

Anyway, what really giving us this function?

**Comment by TheWhisp** [comment]
it's working now

**Comment by SilicaAnimus** [comment]
In case if You will relase build without fully fixed WiFi, but with this
workaround, its possible to make this function just "hardcoded" as disabled
in this build, so its only broking WiFi?

**Comment by TheWhisp** [comment]
Yes, I'll try to disable Wi-Fi optimizations by default. Anyway, it doesn't seem to affect battery life, I left Wi-Fi on for about 9-10 hours and it the battery level only dropped for 5-10 percent more than usual. Deep sleep was working. If that option was working, maybe the battery life would be a little better (when the device is sleeping with Wi-Fi on

**Comment by BrainCruser** [comment]
Workaround works only on charger, not on battery.

**Comment by SilicaAnimus** [comment]
TheWhisp is using currently custom build different from this offcicially
publicated, even with patches from this thread. On him workaround seems to
work. We must wait for next public relase.

**Comment by TheWhisp** [comment]
I guess some people really needs to improve their reading ability :)

**Comment by BrainCruser** [comment]
Or just not be lazy and read everything. Waiting for next build then.

**Comment by SilicaAnimus** [comment]
New build is out. Anyone can confirm that WiFi is working correctly? I'm
curious, but i haven't acces to my phone so I can check this.

**Comment by TheWhisp** [comment]
Yes, I can. It works as good as on CM10 if you've read the change log

**Comment by SilicaAnimus** [comment]
Sorry, I somehow omitted this...

Anyway, workaround is working good. :D
