### ISSUE TITLE
Cm10.1 loosing rigtones setting after restart. 

### ISSUE THREAD

**Issue by SilicaAnimus** [TheWhisp/android_device_samsung_msm7x27a-common#31]
After reboot newest CM 10.1 he losing settings of custom audio files set as ringtone and notification sound.

GT-S6500.

**Comment by TheWhisp** [comment]
I have changed ringtone for Messaging app and Hangouts, they seem to stay there after reboot.

**Comment by SilicaAnimus** [comment]
Strange, I experienced that situation:
1. Putted in /sdcard0/notifications notification ringtone & /sdcard0/ringtones phone ringtone.
2. Set them in System Settings as ringtones.
3. Rebooted into recovery, made backup.
4. rebooted into CM, but there was set default ringtones.
