### ISSUE TITLE
BLN Control...jena

### ISSUE THREAD

**Issue by Peky031** [TheWhisp/android_device_samsung_msm7x27a-common#34]
On lastest build 08/18 BLN control won't work.
Says: This kernel does not support BLN.
Tried with BLN Control-pro :/
Any solution?

**Comment by TheWhisp** [comment]
any more details?

**Comment by Peky031** [comment]
Dunno, here's screenshot...

![screenshot_2013-08-18-23-10-23](https://f.cloud.github.com/assets/5257071/983228/bafc6a92-084a-11e3-8824-862e7c38931b.png)

**Comment by TheWhisp** [comment]
It seems I have forgotten to enable it in the kernel...
