### ISSUE TITLE
Keyboard on PIN lockscreen is cutted. 

### ISSUE THREAD

**Issue by SilicaAnimus** [TheWhisp/android_device_samsung_msm7x27a-common#36]
If we locking our phone with PIN code, buttons on lock screen keyboard are cutted:

![screenshot_2013-08-01-18-59-46](https://f.cloud.github.com/assets/5256217/984954/5fd0dc20-08ae-11e3-9e66-655cb9376afa.png)

**Comment by ghost** [comment]
Same problem on jena, 7/18 build.

**Comment by bqubique** [comment]
Same on trebon Latest build CM10.1.2

**Comment by xzertexz** [comment]
same problem from the first BUILD of cm 10.1

**Comment by leggiero** [comment]
Same problem in the GT-6500

**Comment by TheWhisp** [comment]
buy a device with higher resolution :P

on topic: it just needs to be re-sized. Someone wants to do it - go ahead.

**Comment by bqubique** [comment]
TheWhisp believe me ,if I knew how to do it ,I would do ,at least I would try ,because I'm not so skilled on Android

**Comment by TheWhisp** [comment]
I was just kidding. I'll look into it when I have time. ;)

**Comment by bqubique** [comment]
Oh ok ,great .
TheWhisp what's the reason that you are rarely on xda ,I assume that ypu are in a vacation :D

**Comment by TheWhisp** [comment]
kind of ;)

**Comment by bqubique** [comment]
I hope you finish it soon (for our good )
I hope it never finishes (for our good )

**Comment by bqubique** [comment]
Why is this issue re-opened when thewhisp pushed to his github this issue's fix?

**Comment by TheWhisp** [comment]
it's not fixed

edit: now it is.

**Comment by bqubique** [comment]
thewhisp , will there be a patch about the PIN bug?
