### ISSUE TITLE
video recording / graphical glitches /  wifi

### ISSUE THREAD

**Issue by pitelasssss** [TheWhisp/android_device_samsung_msm7x27a-common#41]
Good afternoon! thanks for all the work
I have a samsung galaxy mini 2 (gts6500D)    ( cm-10.1-20130818-UNOFFICIAL-jena.zip )    and I have problem in graphs, especially when I open the settings. I have internet access on my router but when I try to connect to an outside network wifi not have access

no video after recording, green lines only

**Comment by xzertexz** [comment]
same problem here.
