### ISSUE TITLE
White screen bug Build 20130813 no white screen during 30 minutes

### ISSUE THREAD

**Issue by nadigunawan** [TheWhisp/android_device_samsung_msm7x27a-common#42]
i have installed on jena build 20130813 , after install i tried to lock my device, and i tried to unlock, i got white screen. after that i tried to lock unlock many times during 10 seconds. white screen gone... but after 30 minutes i tried to unlock...unfortunately i got white screen again.

**Comment by ghost** [comment]
This issue has been reported earlier, read the issues before posting a new one.
