### ISSUE TITLE
Can't access to external sdcard

### ISSUE THREAD

**Issue by iformas** [TheWhisp/android_device_samsung_msm7x27a-common#46]
Hi, im new in cyanogemod :)
Im using v 10.120130818-UNOFFICIAL-jena in a Samsumg Galaxy Mini 2 (S-6500L)
When i go to Settings/Storage i can see my sdcard, but i can't access it from the file manager or any other app

Thanks

**Comment by TheWhisp** [comment]
I don't have this problem
