### ISSUE TITLE
Several apps not responding while using mobile network

### ISSUE THREAD

**Issue by ghost** [TheWhisp/android_device_samsung_msm7x27a-common#48]
If I use mobile network, with Wi-Fi off, the phone keeps telling me that some apps are not responding (asking me to close, wait or report).
The apps which I've had problems with: Google search (Google now lags, cards show up after some minutes if the app doesn't close)
-Facebook
-Facebook messenger

Device: GT-S6500D

**Comment by TheWhisp** [comment]
Keep in mind, this is Galaxy Mini 2 not a Galaxy S4.
Anyway, my mobile network is always on (HSDPA) Sync is on. I haven't experienced any FC since the first 3.0.x build I used even when the device update was 120+H
