### ISSUE TITLE
Headsoccer game crash at cyanogenmod Build 18.08.2013 for jena GT-S6500

### ISSUE THREAD

**Issue by shojib97old** [TheWhisp/android_device_samsung_msm7x27a-common#51]
hello everyone in my device the game headsoccer is crashing how i fix this problem???

**Comment by NaokiXie** [comment]
Apps and Games FC(Force Closed/Crash) can be caused by 1) bad coding of game developer and 2). could be fault on CM side.

**Comment by shojib97old** [comment]
it's not bad coding because on my friend's telephone it's working and it's working to me on previous build of cyanogenmod exactly on build Build 13.07.2013

**Comment by TheWhisp** [comment]
You do realize that CM makes changes to their source every day?
