### ISSUE TITLE
Vibration isn't working

### ISSUE THREAD

**Issue by ghost** [TheWhisp/android_device_samsung_msm7x27a-common#58]
When setting the device ring mode to vibrate, it doesn't vibrate: as if I muted it.
Device: GT-S6500D
CM 10.1 build 30/8

**Comment by SilicaAnimus** [comment]
I don't confirm, for me is working good.

**Comment by ghost** [comment]
Well it isn't working for me: I can provide a logcat

**Comment by TheWhisp** [comment]
Working fine.
