### ISSUE TITLE
A2DP playback - media voice transferred  to speaker

### ISSUE THREAD

**Issue by omergo** [TheWhisp/android_device_samsung_msm7x27a-common#67]
Hi,

First I would like to Express appreciation for your work on S6500 this device with CyanogenMod 10.1 works much better than with the official release.

Tested Build: Build 30.08.2013 (G)

Test Device: samsung salaxy mini 2 S6500

Test Applications: Google Play Music , Apollo .

Bug description: When Bluetooth headphones is connected media voice is transferred to speaker instead of A2DP bluetooth sound. As seen in the image attached Bluetooth is connected but the music come out from the speaker.

Screen shot:
![screenshot_2013-09-03-09-59-12](https://f.cloud.github.com/assets/5370410/1070868/479b94e6-1467-11e3-87f8-28cbd917aff3.png)

Log File:
I don't know how to get log file.

Thanks

**Comment by leggiero** [comment]
The same think to skype using a bluetooth headset. The sound is transfered to speaker instead of the connected headset.

**Comment by TheWhisp** [comment]
Can you upload a logcat? I don't have BT headset. We're using unofficial BlueZ stack while 4.2 originally uses Bluedroid, that's why the problem occurs.

**Comment by omergo** [comment]
Hi,
I'm willing to help testing/debugging in order to solve this issue.

**Comment by TheWhisp** [comment]
Probably fixed with the Bluedroid stack. Will re-open until someone confirms that it's still broken
