### ISSUE TITLE
White screen permanently

### ISSUE THREAD

**Issue by micsialdracu** [TheWhisp/android_device_samsung_msm7x27a-common#68]
Hi.
I have S6500D with CM 10.1 build 30.08.2013. 
I've tested latest 4 builds and white screen issue was not a problem for me, until today. Phone starts with white screen, when touching volume keys plays sounds with a little lag, home button and power buttons works but white screen remain.
But, problem is that i have white screen even in recovery mode ( CWM 6.0.3.3 jena) and download mode. I cannot do anything.
 I flashed with Odin 3 v.3.04 original rom and white screen persist. 
After power on,  display turn on in white screen and remain on, then phone vibrate 3 times, periodic.
With the phone off and on charging, white screen appear and  display turn off after few seconds. 
What do you think ? Is there any chances to repair my phone?
Thank you for your answer.

**Comment by micsialdracu** [comment]
TheWisp, is something wrong with my post?

**Comment by micsialdracu** [comment]
All you can do is to close this isssue?

**Comment by NaokiXie** [comment]
Read the previous posts as this question and bug are asked tooooooo many times.
