### ISSUE TITLE
GT-S6500D PUK key sim unlock not working

### ISSUE THREAD

**Issue by ghost** [TheWhisp/android_device_samsung_msm7x27a-common#74]
My phone locked it self while i was at school and when i got home i entered my PUK key this worked but it then asked for a new pin for your sim card. After entering the same pin twice it would flash a few times and then go back to asking for the PUK key i repeated this about five times.

I then unlocked my sim card by using another phone. The normal sim pin unlock worked fine.

Model Number: GT-S6500D
ClockWorkMod: cwm-6.0.3.2-jena-build-4.tar
Android Version: cm-10.1-20130818-UNOFFICIAL-jena.zip

**Comment by TheWhisp** [comment]
Well, I will not even try to reproduce this problem. If anyone else can confirm this with a radio and normal logcat, I will  re-open this issue.
