### ISSUE TITLE
Status Bar Widget

### ISSUE THREAD

**Issue by NaokiXie** [TheWhisp/android_device_samsung_msm7x27a-common#75]
The status bar widget on the upper right sometimes get cropped or missing

![screenshot_2013-09-11-12-45-10](https://f.cloud.github.com/assets/5251131/1123106/7bc16c54-1ae9-11e3-8634-8053f5cc2202.jpg)

![asasaa](https://f.cloud.github.com/assets/5251131/1123144/10669514-1aea-11e3-9352-cd0847ecdfbb.jpg)

EDIT: CM10.1 build 07/18

**Comment by pgcristyan** [comment]
I never experienced such a problem, and i'm suspecting you experience it because you made your status bar transparent by installing something.

**Comment by TheWhisp** [comment]
no problems for me either
