### ISSUE TITLE
cLock widget bug (spanish version)

### ISSUE THREAD

**Issue by Silverhanwk** [TheWhisp/android_device_samsung_msm7x27a-common#76]
I've installed the last build of CM 10.1. Everything works fine, but there is a bug with cLock widget (Lockscreen). The problema is that I can't see the day. I just see the month. 

![screenshot_2013-09-13-18-53-22](https://f.cloud.github.com/assets/5354016/1142539/db57e560-1cd5-11e3-8558-5e16590a34b5.png)

Sorry for my bad english.

**Comment by TheWhisp** [comment]
It's because of the screen resolution.
