### ISSUE TITLE
Call, SMS, WiFi not working( First time on CM )

### ISSUE THREAD

**Issue by ghost** [TheWhisp/android_device_samsung_msm7x27a-common#78]
Today i have installed CM 10.1 Build 11.09.2013 (G) for first time and i cant call, send sms or connect to 3G or WiFi
What i have to do to fix it ?

**Comment by ahmedmo97** [comment]
try to re-install the rom and wipe data

**Comment by ghost** [comment]
i have tried, nothing changing
