### ISSUE TITLE
Vpn Problem

### ISSUE THREAD

**Issue by abunet** [TheWhisp/android_device_samsung_msm7x27a-common#81]
HI,
I can't connect to my office PPPTP VPN with my GT-S7500 and your great cyano 10.1.
I can see in logcat the following error:
Creating PPPoX socket
Socket() Protocol not supported

Are any ppp kernel module missing?

Thanks!

**Comment by TheWhisp** [comment]
don't report trebon bugs, it's builds are outdated.

**Comment by abunet** [comment]
Sorry, but where can I find the latest builds? 

The last I've found are at http://goo.im/devs/thewhisp/trebon-cm10.1 (2013-07-13).
