### ISSUE TITLE
Download Manager: can't open or hide downloaded files from notification drawer.

### ISSUE THREAD

**Issue by iljyxa** [TheWhisp/android_device_samsung_msm7x27a-common#88]
If try open or hide any files in notifications drawer, downloaded with Download Manager, then they vanish and randomly come back (maybe not random, i don't know). After this i need Clear data, else i receive this notification again and again.

com.android.providers.downloads
jenad, 10.2

**Comment by TheWhisp** [comment]
not device-specific
