### ISSUE TITLE
Wifi MAC address

### ISSUE THREAD

**Issue by NaokiXie** [TheWhisp/android_device_samsung_msm7x27a-common#90]
MAC address changes after flashing the latest build.

Device: GT-S6500D
Build: cm10.1-20130920

**Comment by SilicaAnimus** [comment]
There is no such build. :P

Anyway, the WiFi driver does not have some Samsung specific code, so he cannot read phone's MAC and using randomly generated adres.

**Comment by NaokiXie** [comment]
yeah .it cannot read the efs.

also no spoofers are working on it.

**Comment by iformas** [comment]
Hi, i have the build 20130818 and i have a very slow reconection  rate, poor WiFi performance and disconnections under sleep (with WiFi optimization disabled).. All these bug are fixed in the last build?

**Comment by SilicaAnimus** [comment]
No, but in build 20130920 it is working absollutelly well. Also it will be
fixed in nearest future relase.

**Comment by iformas** [comment]
Thanks for the info

**Comment by NaokiXie** [comment]
@TheWhisp since we're rolling back to compat-wireles... do wifi mac address will also be fix?

**Comment by TheWhisp** [comment]
Every build with 3.0.x kernel has ath6kl from compat-wireless.

**Comment by TheWhisp** [comment]
This is partially fixed now. The MAC address should be different for every build now, but it is still incorrect.

**Comment by TheWhisp** [comment]
Fixed
