### ISSUE TITLE
Twitch.tv and Live Streaming App On Jena

### ISSUE THREAD

**Issue by Xiphled** [TheWhisp/android_device_samsung_msm7x27a-common#93]
Any kind of streaming app that i have found so far doesn't work, whenever you select a stream it displays a black screen. Sometimes sound can be heard but only for a second or so.I am using the latest stable build(20.09.2013) with no extra modification what-so-ever. I hope you can fix this Whisp, I use my phone to watch live streams a lot and i love jellybean and your work, would be a shame if this remains unfixed. Thank you! You're legen - wait for it - DARY! :+1: 
If you need any extra info I'd be glad to help, so just ask !

**Comment by TheWhisp** [comment]
no logs, invalid

**Comment by Xiphled** [comment]
Do you need a logcat? If so, i'll add it here.
