### ISSUE TITLE
Twitch.tv and LiveStream App + Logcat

### ISSUE THREAD

**Issue by Xiphled** [TheWhisp/android_device_samsung_msm7x27a-common#95]
http://www.mediafire.com/?bb5a58db9ddb9b5 - LOGCAT.

Any live streaming app I've tried does NOT work. Sound can be heard but only for a second, changing the quality didn't help either.

 I tried using the attach feature but it only supports images. I would really appreciate if you'd take me easy if you need something, not all of us have the knowledge you do, but I'm willing to learn.I hope you can look into it, if you simply dont want to, tell me, nobody's forcing you. I know you don't spend all day doing this and I haven't asked you to solve it in 30 seconds, I've just reported a bug.

**Comment by TheWhisp** [comment]
there is a segmentation fault. Probably the old OMX libs are incompatible

**Comment by Xiphled** [comment]
Anything you can do to fix it? I'd appreciate it, take your time doing it though :-)

**Comment by iformas** [comment]
Also i cant see youtube streams :(

**Comment by Peky031** [comment]
+1 cant stream youtube in desktop view!

**Comment by TheWhisp** [comment]
Fixed

**Comment by Xiphled** [comment]
Thank you! :)
