### ISSUE TITLE
Wi-Fi loosing connection!

### ISSUE THREAD

**Issue by Peky031** [TheWhisp/android_device_samsung_msm7x27a-common#98]
On lastest build 29.9, when i lock the screen Wi-Fi turn off... and Wi-FI optimization is unchecked... is it bug or?

**Comment by NaokiXie** [comment]
+1, wifi turns off even wifi optimization is disabled.

**Comment by TheWhisp** [comment]
wait for the next build, or use ath6kl.ko from previous ROM
