### ISSUE TITLE
Deep Sleep

### ISSUE THREAD

**Issue by NaokiXie** [TheWhisp/android_device_samsung_msm7x27a-common#99]
The excessive battery loss is because the phone doesn't enter deep sleep.

Build: CM10.1-20130929
Model: GT-S6500D

**Comment by TheWhisp** [comment]
no problems for me

**Comment by erikcas** [comment]
He Davis, I checked, have deepsleep problem too. I suspect the wifi change. When I turn off wifi, it enters deepsleep as expected. Will check it over my holidays.

**Comment by TheWhisp** [comment]
it could happen because of the updated aht6kl-compat. Wi-Fi is kind of unstable now. Need  to revert to compat-wireless-3.9

**Comment by ghost** [comment]
I have the same issue. My phone always drains to 0% overnight.

**Comment by erikcas** [comment]
That kind of drain I donot experience....

**Comment by TheWhisp** [comment]
@Bibicp That's definitely your problem. My phone has been about 20h on battery, little Wi-Fi usage + Hill Climb Racing - went from 100 to 80 percent.

**Comment by ghost** [comment]
Explain how this is my problem.. This doesn't happen on 20/9 build.
My battery was at 60%, and then in the morning it was 0%..

**Comment by NaokiXie** [comment]
never experience something like that.
i have same with thewhisp. some sms and wifi. 100% to 76% on 20hrs 3mins.

maybe your battery is faulty.

**Comment by NaokiXie** [comment]
Its seems to be marked as fixed.. So were rolling back to compat-wireless?.. Do wifi-mac also be fixed?
